security:
  oauth2:
    client:
      client-id: cliente
      client-secret: password
      scope: read,write
      auto-approve-scopes: '.*'
server:  port: 8701
  tomcat:    threads:      max: 2
spring:
  datasource:    
    #type: com.zaxxer.hikari.HikariDataSource
    #driver-class-name: com.mysql.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/itaid?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
#    url: jdbc:sybase:Tds:201.161.87.114:2638/graficas
    url: jdbc:sybase:Tds:201.161.95.49:2638/alm_lab_nube
   # username: dba
   # password: ###

    
    #hikari:
     # connection-timeout: 30000              # La cantidad máxima de tiempo (en milisegundos) para esperar a que el grupo de conexiones asigne una conexión. Si la conexión no está disponible por más de esta longitud, se producirá SQLException. El valor predeterminado:30segundo 
      #minimum-idle: 2                                  # Número mínimo de conexiones
    #  maximum-pool-size: 4                      # Número máximo de conexiones
     # auto-commit: true                              # Envío automático
      #idle-timeout: 600000                        # La duración máxima del tiempo de espera de la conexión (milisegundos), el tiempo de espera se liberará (retirado), predeterminado:10Minutos
     # idle-timeout: 120000                         # La duración máxima del tiempo de espera de la conexión (milisegundos), el tiempo de espera se liberará (retirado), predeterminado:10Minutosidle-timeout: 600000                        # La duración máxima del tiempo de espera de la conexión (milisegundos), el tiempo de espera se liberará (retirado), predeterminado:10Minutos
     # pool-name:  DateSourceHikariCP_SYBASES_WSINV # Nombre del grupo de conexiones
      #max-lifetime: 1800000                      # El tiempo de vida de la conexión (milisegundos), se liberará si se agota el tiempo de espera y no se usa (retirado), por defecto:30minuto 1800000ms
     # max-lifetime: 60000                      # El tiempo de vida de la conexión (milisegundos), se liberará si se agota el tiempo de espera y no se usa (retirado), por defecto:30minuto 1800000ms
     # leak-detection-threshold: 1000
  
  jpa:    
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  main:
    allow-bean-definition-overriding: true 